services:
  mysql:
    image: mysql:9.3.0
    container_name: api_rev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_password
      MYSQL_DATABASE: revisao_db
      MYSQL_USER: revisao_user
      MYSQL_PASSWORD: revisao_user_password
    ports:
      - "3406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network

volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge